from .generateData import setting2_generateData


# Функция для генерации массива данных для запроса для настройки 2
def setting2_getDataArray():
    # Массив дат с нужными параметрами для запроса
    dataArray = [
        setting2_generateData(
            "vanessadior.xo",
            "1IP_aPES-NB60xVctiovJd5oEDjVqGV3G",
            "1T4WxLRaQWeIf8m-JSts07-k4dFKmfq5O",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 2.5, 1, -1.05, -1.5],
        ),
        setting2_generateData(
            "cleawynn",
            "1zkKTh7qhTT3iGhPm1gzS6U52_5w7lRwl",
            "1piJm_qahhVFKwUY6FBaWC0KW_-ar-Jcl",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 1.50, -0.20, -0.95, -1.50],
        ),
        setting2_generateData(
            "celinemyrren",
            "1zL7OWlFfEdOFl_bvnLIKoEe8VVspE5Fn",
            "1wepiHdwKQ8xQBVKhPaUxLgL_BOYbKXjM",
            """brown hair, green eyes, tan skin""",
            [1, 1, 2.05, 0.05, -0.15, -1.5],
        ),
        setting2_generateData(
            "gracelowell.xo",
            "1KQZimxqXua-vF8-_7gUIenrU5C544r5M",
            "1OG4YeEvj2Rlo4CrUWtvtVciT-DMQpaFZ",
            """blonde hair, green eyes, tan skin""",
            [1, 1, 2.05, 0.05, -0.85, -1.5],
        ),
        setting2_generateData(
            "valeriagomez.xo",
            "1ksAaqiUNxX_8AcxLNcZGFgyGNjuz97fo",
            "1-VU7GIe8nV4hTNRhk9X4c62fGQ1pWwln",
            """black hair, brown eyes, dark tan skin""",
            [1, 1, 2.40, 0.55, -0.35, -1.5],
        ),
        setting2_generateData(
            "ivyxhart",
            "1v1-rA4z3eRk8AuO-rNt9-nKhiQCe2A4i",
            "1fok6e3RKfWe2gs-IR4tPjoVh0IC6k9l2",
            """black hair, brown eyes, dark tan skin""",
            [1, 1, 2.40, 0.55, -1.70, -1.5],
        ),
        setting2_generateData(
            "ellamaddix.xo",
            "1gtcEggKrbNMDE8ceykHylGSV0WQa1win",
            "1ituzRBr7mIXdVdjKplVWMcwVYV3Ekjc5",
            """blonde hair, green eyes, tan skin""",
            [1, 1, 0.40, 0.50, -0.95, -1.50],
        ),
        setting2_generateData(
            "mileyleclair.xo",
            "1wSgokKf7KtaM9Pk6k4eMvTvbKbZbZnpN",
            "15PJT6LxJh1wdqCs5God9rOhjfprvF1Ab",
            """blonde hair, green eyes, tan skin""",
            [1, 1, 2.00, 1.20, -2.70, -1.50],
        ),
        setting2_generateData(
            "thea_azelle",
            "1xmfOthCO11uXY0P4vmePeiqB5m0CqT8x",
            "1cH6zixQYYZqVfo7jj1x6V47SAOruv5mb",
            """blonde hair, brown eyes, dark tan skin""",
            [1, 1, 1.00, 0.30, -1.20, -1.50],
        ),
        setting2_generateData(
            "briaclaire.xo",
            "1yRr_qWf3oi0Re9MRSCFuNx96WZltPcx_",
            "1_w-ME7mXI5GbkbmKUzSBIongXPL-NEmO",
            """brown hair, blue eyes, tan skin""",
            [1, 1, 4.00, 0.50, -1.70, -1.5],
        ),
        setting2_generateData(
            "rinazuri.xo",
            "16kfOvHl49oYtjQwWCti-6XQFbaFhmk4R",
            "1A9x1vWllbCV0RdkTIgaXH-tw5uYhtd3p",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 3.00, 0.30, -0.80, -1.50],
        ),
        setting2_generateData(
            "mari_avellin",
            "1byOhjOqAv1jls_fixANmpgZJaJaub17E",
            "1SwwlT6BneWXHnIXBrVplpAr2u7V4v7rY",
            """blonde hair, brown eyes, dark tan skin""",
            [1, 1, 1.00, -0.10, -0.60, -1.50],
        ),
        setting2_generateData(
            "amirawellex",
            "1zJBDXAWf_zQJTMwWO_IZsYow3y317b0d",
            "1HhN2Y_IX3mNRqsHjoNW-mQoVsnrkFAhX",
            """black hair, blue eyes, tan skin, asian""",
            [1, 1, 2.75, 0.15, -1.30, -1.5],
        ),
        setting2_generateData(
            "dianadelmar.xo",
            "1HhN2Y_IX3mNRqsHjoNW-mQoVsnrkFAhX",
            "10ZLClflAS1iuPp2NO5lOdbaqPMH1sUkR",
            """brown hair, blue eyes, tan skin, asian""",
            [1, 1, 3.70, 1.35, -2.40, -1.50],
        ),
        setting2_generateData(
            "kaiastell",
            "1l_7AHjkOnWLUEiCZSlOD7GNg5am6akcY",
            "1m_wGBpS8G8QqZGYYEmPZnhvclT7ErTFr",
            """brown hair, blue eyes, tan skin, asian""",
            [1, 1, 3.20, 1.45, -0.20, -1.5],
        ),
        setting2_generateData(
            "ruthmonclaire",
            "1fZ2qgurQZxENOq_XTCQfOpHLKEMf15c_",
            "1tT8bXGlfK3s_rBtrwUg98uho_zhDfeRK",
            """red hair, blue eyes, tan skin, asian""",
            [1, 1, 2.25, 1.10, -1.70, -1.5],
        ),
        setting2_generateData(
            "kenzienoir",
            "17lnjZ_ZB6wtssENq97wK8mjAmXPPyL_r",
            "1sIIRN-fFycdrzGZ5TplcgBeagBc_ThiX",
            """blonde hair, blue eyes, tan skin, asian""",
            [1, 1, 1.55, 0.75, -0.75, -1.5, 1.1],
        ),
        setting2_generateData(
            "janiceblair.xo",
            "1bT3uziNLJ8Zq6uBSpplB8rQ18Hq7tlV8",
            "16ZjV-6wGY16LfF9cx__Y1G7EAgC76QY6",
            """black hair, blue eyes, tan skin""",
            [1, 1, 0.90, 2.35, 0.50, -1.5],
        ),
        setting2_generateData(
            "monikaroxley",
            "1qZhjbfxJOu2Ugrg6p6e4ALdKtbEsT2cO",
            "1lrvYzT3UJ2MSIhjMLZZrSxlGoRKFn3Q_",
            """black hair, blue eyes, tan skin""",
            [1, 1, 0.90, 2.35, 0.50, -1.5],
        ),
        setting2_generateData(
            "kiaravouxelle",
            "1JRvpkAySSaf8Uc3DPBZcxRe9FUYro5Oo",
            "1bQdKmnSDPRe2TUhvfaMPLpXGvZOFZ6pl",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 2.05, 1.35, -1.15, -1.5, 1.1],
        ),
        setting2_generateData(
            "lilith_rayne.xo",
            "1QwVn6hG-HlK8y_MWxc211fWm4t6Khmq2",
            "1lO4VSIW1z1zPSCM2FVcHVJP0yITAHTiL",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 2.00, 1.00, -2.30, -1.50],
        ),
        setting2_generateData(
            "nicolevalaine",
            "1RmU48_mA8J3V4jukG0Eqvbqb5i0kMDfg",
            "1oUHrR7NSfRijwb8epjSIRpQA-xwBsX2i",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 2.30, 1.20, -2.55, -1.50],
        ),
        setting2_generateData(
            "kellymavrix",
            "1cOvzr5OeGyEA1Y2iay5Qt0yObHkPgfar",
            "1iENAftqAUWhYsk_SSL25Ga0bMI197gcB",
            """blonde hair, blue eyes, tan skin""",
            [1, 1, 3.45, 0.05, -1.70, -1.5],
        ),
        setting2_generateData(
            "emilyzaylen",
            "1pnfcAoP4fhG-UdCOfBM-onRX1KaX5EaA",
            "1lnUvluFwFK-zVMemOvMlBPkSCf__YpBQ",
            """brown hair, blue eyes, tan skin, latina""",
            [1, 1, 1.10, 0.05, -1.70, -1.5],
        ),
        setting2_generateData(
            "albabloomy",
            "1Zghq9vHTApUWM3bshy5LwxRK9mWIewat",
            "1S4iSj2VO492lC_b-_8mQa8SKzqr0FZYN",
            """black hair, blue eyes, tan skin, latina""",
            [1, 1, 3.50, 0.05, -3.00, -1.50],
        ),
    ]

    return dataArray
