server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: main_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: bot
          __path__: /var/log/Logs.log

  - job_name: backup_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: bot_backups
          __path__: /var/log/backups/*/logs.log


