name: CI/CD for Focuuus Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: ${{ false }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ls -la ~/.ssh  # Проверка наличия ключа

      - name: Test SSH connection
        run: |
          ssh root@45.80.68.81 "echo 'SSH connection successful'"

      - name: Deploy to server
        run: |
          ssh root@45.80.68.81 << 'EOF'
          cd ..
          cd FocuuusBotFolder/FocuuusBot
          git pull origin master
          sudo systemctl restart focuuusbot.service
          EOF
